// F1 World Drivers' Champions, 1950–2025.
// Historical fact — hardcoded deliberately rather than fetched, since this
// data never changes and Jolpica has no cross-season query endpoint.
// The current season is intentionally absent (shown as "in progress").

export type Champion = {
  familyName: string;
  constructorId: string;
  constructorName: string;
};

export const champions: Record<string, Champion> = {
  "1950": { familyName: "Farina", constructorId: "alfa", constructorName: "Alfa Romeo" },
  "1951": { familyName: "Fangio", constructorId: "alfa", constructorName: "Alfa Romeo" },
  "1952": { familyName: "Ascari", constructorId: "ferrari", constructorName: "Ferrari" },
  "1953": { familyName: "Ascari", constructorId: "ferrari", constructorName: "Ferrari" },
  "1954": { familyName: "Fangio", constructorId: "mercedes", constructorName: "Maserati / Mercedes" },
  "1955": { familyName: "Fangio", constructorId: "mercedes", constructorName: "Mercedes" },
  "1956": { familyName: "Fangio", constructorId: "ferrari", constructorName: "Ferrari" },
  "1957": { familyName: "Fangio", constructorId: "maserati", constructorName: "Maserati" },
  "1958": { familyName: "Hawthorn", constructorId: "ferrari", constructorName: "Ferrari" },
  "1959": { familyName: "Brabham", constructorId: "cooper", constructorName: "Cooper" },
  "1960": { familyName: "Brabham", constructorId: "cooper", constructorName: "Cooper" },
  "1961": { familyName: "Hill", constructorId: "ferrari", constructorName: "Ferrari" },
  "1962": { familyName: "Hill", constructorId: "brm", constructorName: "BRM" },
  "1963": { familyName: "Clark", constructorId: "lotus", constructorName: "Lotus" },
  "1964": { familyName: "Surtees", constructorId: "ferrari", constructorName: "Ferrari" },
  "1965": { familyName: "Clark", constructorId: "lotus", constructorName: "Lotus" },
  "1966": { familyName: "Brabham", constructorId: "brabham", constructorName: "Brabham" },
  "1967": { familyName: "Hulme", constructorId: "brabham", constructorName: "Brabham" },
  "1968": { familyName: "Hill", constructorId: "lotus", constructorName: "Lotus" },
  "1969": { familyName: "Stewart", constructorId: "matra", constructorName: "Matra" },
  "1970": { familyName: "Rindt", constructorId: "lotus", constructorName: "Lotus" },
  "1971": { familyName: "Stewart", constructorId: "tyrrell", constructorName: "Tyrrell" },
  "1972": { familyName: "Fittipaldi", constructorId: "lotus", constructorName: "Lotus" },
  "1973": { familyName: "Stewart", constructorId: "tyrrell", constructorName: "Tyrrell" },
  "1974": { familyName: "Fittipaldi", constructorId: "mclaren", constructorName: "McLaren" },
  "1975": { familyName: "Lauda", constructorId: "ferrari", constructorName: "Ferrari" },
  "1976": { familyName: "Hunt", constructorId: "mclaren", constructorName: "McLaren" },
  "1977": { familyName: "Lauda", constructorId: "ferrari", constructorName: "Ferrari" },
  "1978": { familyName: "Andretti", constructorId: "lotus", constructorName: "Lotus" },
  "1979": { familyName: "Scheckter", constructorId: "ferrari", constructorName: "Ferrari" },
  "1980": { familyName: "Jones", constructorId: "williams", constructorName: "Williams" },
  "1981": { familyName: "Piquet", constructorId: "brabham", constructorName: "Brabham" },
  "1982": { familyName: "Rosberg", constructorId: "williams", constructorName: "Williams" },
  "1983": { familyName: "Piquet", constructorId: "brabham", constructorName: "Brabham" },
  "1984": { familyName: "Lauda", constructorId: "mclaren", constructorName: "McLaren" },
  "1985": { familyName: "Prost", constructorId: "mclaren", constructorName: "McLaren" },
  "1986": { familyName: "Prost", constructorId: "mclaren", constructorName: "McLaren" },
  "1987": { familyName: "Piquet", constructorId: "williams", constructorName: "Williams" },
  "1988": { familyName: "Senna", constructorId: "mclaren", constructorName: "McLaren" },
  "1989": { familyName: "Prost", constructorId: "mclaren", constructorName: "McLaren" },
  "1990": { familyName: "Senna", constructorId: "mclaren", constructorName: "McLaren" },
  "1991": { familyName: "Senna", constructorId: "mclaren", constructorName: "McLaren" },
  "1992": { familyName: "Mansell", constructorId: "williams", constructorName: "Williams" },
  "1993": { familyName: "Prost", constructorId: "williams", constructorName: "Williams" },
  "1994": { familyName: "Schumacher", constructorId: "benetton", constructorName: "Benetton" },
  "1995": { familyName: "Schumacher", constructorId: "benetton", constructorName: "Benetton" },
  "1996": { familyName: "Hill", constructorId: "williams", constructorName: "Williams" },
  "1997": { familyName: "Villeneuve", constructorId: "williams", constructorName: "Williams" },
  "1998": { familyName: "Häkkinen", constructorId: "mclaren", constructorName: "McLaren" },
  "1999": { familyName: "Häkkinen", constructorId: "mclaren", constructorName: "McLaren" },
  "2000": { familyName: "Schumacher", constructorId: "ferrari", constructorName: "Ferrari" },
  "2001": { familyName: "Schumacher", constructorId: "ferrari", constructorName: "Ferrari" },
  "2002": { familyName: "Schumacher", constructorId: "ferrari", constructorName: "Ferrari" },
  "2003": { familyName: "Schumacher", constructorId: "ferrari", constructorName: "Ferrari" },
  "2004": { familyName: "Schumacher", constructorId: "ferrari", constructorName: "Ferrari" },
  "2005": { familyName: "Alonso", constructorId: "renault", constructorName: "Renault" },
  "2006": { familyName: "Alonso", constructorId: "renault", constructorName: "Renault" },
  "2007": { familyName: "Räikkönen", constructorId: "ferrari", constructorName: "Ferrari" },
  "2008": { familyName: "Hamilton", constructorId: "mclaren", constructorName: "McLaren" },
  "2009": { familyName: "Button", constructorId: "brawn", constructorName: "Brawn GP" },
  "2010": { familyName: "Vettel", constructorId: "red_bull", constructorName: "Red Bull" },
  "2011": { familyName: "Vettel", constructorId: "red_bull", constructorName: "Red Bull" },
  "2012": { familyName: "Vettel", constructorId: "red_bull", constructorName: "Red Bull" },
  "2013": { familyName: "Vettel", constructorId: "red_bull", constructorName: "Red Bull" },
  "2014": { familyName: "Hamilton", constructorId: "mercedes", constructorName: "Mercedes" },
  "2015": { familyName: "Hamilton", constructorId: "mercedes", constructorName: "Mercedes" },
  "2016": { familyName: "Rosberg", constructorId: "mercedes", constructorName: "Mercedes" },
  "2017": { familyName: "Hamilton", constructorId: "mercedes", constructorName: "Mercedes" },
  "2018": { familyName: "Hamilton", constructorId: "mercedes", constructorName: "Mercedes" },
  "2019": { familyName: "Hamilton", constructorId: "mercedes", constructorName: "Mercedes" },
  "2020": { familyName: "Hamilton", constructorId: "mercedes", constructorName: "Mercedes" },
  "2021": { familyName: "Verstappen", constructorId: "red_bull", constructorName: "Red Bull" },
  "2022": { familyName: "Verstappen", constructorId: "red_bull", constructorName: "Red Bull" },
  "2023": { familyName: "Verstappen", constructorId: "red_bull", constructorName: "Red Bull" },
  "2024": { familyName: "Verstappen", constructorId: "red_bull", constructorName: "Red Bull" },
  "2025": { familyName: "Norris", constructorId: "mclaren", constructorName: "McLaren" },
};